### ISSUE TITLE
Logical error in Range.intersectionHelper

### ISSUE THREAD

**Issue by aleksator** [mpizenberg/elm-pubgrub#17]
Hi! While looking through the code, I noticed that [the following piece](https://github.com/mpizenberg/elm-pubgrub/blob/master/src/PubGrub/Range.elm#L239-L240) is not true:
```
            if not (Version.lowerThan l2 r1) then
                -- Intervals are disjoint since l2 <= r1
```
not less === more or equals. The code should probably call `Version.higherThan` instead of `Version.lowerThan` to match the comment.

[Similarly later](https://github.com/mpizenberg/elm-pubgrub/blob/master/src/PubGrub/Range.elm#L243-L244):
```
            else if not (Version.lowerThan r2 l1) then
                -- Intervals are disjoint since r22 <= l1
```
should use `Version.higherThan`. Also, there's a small typo with `r22` ;)

Same thinking can be extended further down the function.

The algorithm as a whole seems to be working according to the demo, so I wonder if that's me who's delusional with these conclusions, or maybe that's just a happy coincidence (or potentially another bug covering it up).

**Comment by mpizenberg** [comment]
I guess I should have added a doc comment for `lowerThan` and `higherThan`. The "Than" part was to give a hint that you could use this in a pipe situation:
```elm
v1
    |> lowerThan v2
```
actually means `v1 < v2` but when I write it in a single line as `lowerThan v2 v1` the versions seem reversed.

Thanks for the typo! Let me know if you want to do you want to do a PR? (with dev branch)

**Comment by mpizenberg** [comment]
By the way, I just randomly checked some doc comments and spotted an issue in the one of `Term.union` so I've just fixed that one now. Still in dev branch but letting you know in case you had already spotted it.

**Comment by aleksator** [comment]
> I guess I should have added a doc comment for `lowerThan` and `higherThan`. The "Than" part was to give a hint that you could use this in a pipe situation:
> 
> ```elm
> v1
>     |> lowerThan v2
> ```
> 
> actually means `v1 < v2` but when I write it in a single line as `lowerThan v2 v1` the versions seem reversed.

Ah, I see where my confusion stems from. Indeed, I didn't expect that and even though I looked inside the implementation of `lowerThan` I still didn't catch that it produces the opposite of what I thought it does. Thank you for the clarification.

> Thanks for the typo! Let me know if you want to do you want to do a PR? (with dev branch)

Actually I noticed quite a few throughout the code, so I'd rather do a big one later that proofreads the whole project than submit a bunch of PRs with 1 symbol changes. Somehow it bothers me that the git history get "polluted" with tiny changes and makes the project evolution harder to track.

> By the way, I just randomly checked some doc comments and spotted an issue in the one of Term.union so I've just fixed that one now. Still in dev branch but letting you know in case you had already spotted it.

I didn't actually notice you have a dev branch with an ongoing development, that's awesome! I thought this project came to a halt about 2 months ago when there was a last commit on master.

I probably won't be able to contribute much code since this codebase is the first piece of Elm code I ever had a look at. I'm just that interested in the algorithm and studying it through the original Dart implementation and now this one (found through some issue in the original project), which I think is very clean and is a pleasure to read - props to you!

Is there a way to contact you other than Github issues (say, Discord) if i have questions like this in the future? If you want to keep communication contained here, that's also fine.

**Comment by mpizenberg** [comment]
Thanks for the kind words. Actually it did come to a halt, because I'm kind of waiting for [elm-minithesis](https://github.com/Janiczek/elm-minithesis) to be published so that I can add property based testing to this (cf few commits in dev branch). And I also have had less time.

The order of arguments favouring piping is actually something found quite a lot in elm code. But in that exact case for such a small function it may not have been the right choice, I don't know. What's for sure is that there needs to be an example usage in the doc comment, otherwise confusion is certain.

Regarding the original dart implementation, elm-pubgrub may be very different since I actually almost never looked at it, except very punctually for a few things. I exclusively followed the [readme documentation](https://github.com/dart-lang/pub/blob/master/doc/solver.md). The pure functional nature of elm also forced changes so it would never have been the same anyway.

For discussions, you can use the elm slack if you want but I may be less reactive since I do not keep it open. I can respond to private messages on the elm discourse also if you prefer. Otherwise github issues are totally fine too.

**Comment by aleksator** [comment]
I saw you were focusing on testing in the dev branch. Make sense if you think the core of the algorithm is almost ready.
Thank you for letting me know the other ways to reach out, I'll keep them in mind.

I'm closing this issue since the code actually works correctly.

**Comment by mpizenberg** [comment]
> I'm just that interested in the algorithm and studying it through the original Dart implementation and now this one

Hi @aleksator if you don't mind, I also have some questions for you. Where should I direct them?

**Comment by aleksator** [comment]
Hi. You can reach me out on Discord: Gwentology#8908.
