### ISSUE TITLE
Example 1 is solved with wrong steps

### ISSUE THREAD

**Issue by malaire** [mpizenberg/elm-pubgrub#4]
Output of solving Example 1:
```
> import PubGrub
> import Version
> PubGrub.solve "root" Version.one
Add the following 1 incompatibilities from dependencies of root: ""
   root: 1.0.0, foo: Not ( 1.0.0 <= v < 2.0.0 )  <<<  from dependency of root at version 1.0.0: ""
Decision level 1 : root : 1.0.0: ""
Derivation : foo : 1.0.0 <= v < 2.0.0: ""
Add the following 1 incompatibilities from dependencies of foo: ""
   foo: 1.0.0, bar: Not ( 1.0.0 <= v < 2.0.0 )  <<<  from dependency of foo at version 1.0.0: ""
Decision level 2 : foo : 1.0.0: ""
Derivation : bar : 1.0.0 <= v < 2.0.0: ""
Add the following 0 incompatibilities from dependencies of bar: ""
Decision level 3 : bar : 1.0.0: ""
Ok [("bar",Version { major = 1, minor = 0, patch = 0 }),("foo",Version { major = 1, minor = 0, patch = 0 }),("root",Version { major = 1, minor = 0, patch = 0 })]
```
Comparing this to [the exact steps algorithm should take](https://github.com/dart-lang/pub/blob/master/doc/solver.md#no-conflicts), `elm-pubgrub` at least uses incorrect decision level numbers while solving this example.

**Comment by mpizenberg** [comment]
Yeah decision level spec is very unclear in the spec actually. And the start of the algorithm I add an incompatibility that generates a derivation that will be added to the partial solution first (thus with level = 0). Then the decision for root is added, making it level 1. I don't thing this is much of an issue, the algorithm doesn't seem to be reliant on which level is the first one.

**Comment by mpizenberg** [comment]
Also as I think of it now, I remember that the order in the examples rely on the strategy used to choose the next package/version. The thing I've implemented just take the first one in the list. That's why I still have a `List.reverse` in example 3: https://github.com/mpizenberg/elm-pubgrub/blob/3a36cd3ed2dd4c0278fff6316b57b9411c35b1cf/src/Database/Stub.elm#L127

As I remember it, At the time I was testing this, I've tried reversing lists of stuff. But maybe there is still an issue that I didn't spot!

**Comment by mpizenberg** [comment]
The example step-by-step solutions are a bit simplified and not totally accurate with the detailed PubGrub implementation. They are more guidelines than accurate algorithm steps. For example, note that the description says

> decision level 1 is the level where the root package was selected

while the example table uses level 0 for this. Level 1 is the correct choice since the algorithms actually starts with

> Begin by adding an incompatibility indicating that the current version of the root package must be selected (for example, {not root 1.0.0}).

Which should be in the table just before step 1. In turn, that incompatibility triggers the add of the derivation `root 1.0.0`, which should also appear before. Finally, that derivation which must have a level (so level 0 is given to it) triggers the addition of the decision `root 1.0.0`. Decisions added to the partial solution automatically increment the decision level, which means it has to be 1 since the previous derivation already has level 0.

PS: to see in the log the add of that level 0 derivation `root 1.0.0`, we should add a debug log in the first branch of `PartialSolution.prependDerivation`.
